name: Sync auto_push branch with master
on:
  push:
    branches:
        - master
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: git checkout origin/auto_push
      - name: Fetch latest changes from master
        run: git fetch origin master
      - name: Merge changes from master
        run: |
            git merge origin/master --no-ff --no-edit
            git push origin auto_push
